// =========================================================
// Anonymoux Studio — backend
// =========================================================
// Express server for Anonymoux Studio.
//
// Responsibilities:
//   1. Serve the frontend.
//   2. Keep FAL_KEY on the server.
//   3. Proxy fal.ai requests through /api/fal/proxy.
//
// IMPORTANT:
// We intentionally do NOT create our own WebSocket server here.
// @fal-ai/client handles the realtime WebSocket connection.
// The fal.ai proxy receives the authentication/HTTP requests
// generated by the client and attaches the server-side FAL_KEY.
// =========================================================

require("dotenv").config();

const express = require("express");
const fetch = require("node-fetch");
const path = require("path");

const app = express();

const PORT = process.env.PORT || 3000;
const FAL_KEY = process.env.FAL_KEY;

// =========================================================
// Configuration
// =========================================================

const ALLOWED_HOSTS = [
  "fal.run",
  "queue.fal.run",
  "fal.ai",
  "api.fal.ai",
  "rest.fal.ai",
  "rest.alpha.fal.ai"
];

// =========================================================
// Startup validation
// =========================================================

if (!FAL_KEY) {
  console.error("");
  console.error("========================================");
  console.error("ERROR: FAL_KEY IS NOT SET");
  console.error("========================================");
  console.error("");
  console.error(
    "Set FAL_KEY in your Render Environment Variables."
  );
  console.error("");
} else {
  console.log("[startup] FAL_KEY configured.");
}

// =========================================================
// Helpers
// =========================================================

function isAllowedTarget(targetUrl) {
  try {
    const parsed = new URL(targetUrl);

    const hostname = parsed.hostname.toLowerCase();

    return ALLOWED_HOSTS.some(
      (allowedHost) =>
        hostname === allowedHost ||
        hostname.endsWith("." + allowedHost)
    );
  } catch {
    return false;
  }
}

// =========================================================
// Health check
// =========================================================

app.get("/api/health", (req, res) => {
  res.json({
    ok: true,
    service: "Anonymoux Studio",
    falKeyConfigured: Boolean(FAL_KEY),
    proxy: "/api/fal/proxy"
  });
});

// =========================================================
// FAL PROXY
// =========================================================
//
// The @fal-ai/client sends the actual fal.ai destination
// in the x-fal-target-url header.
//
// We:
//   1. Read the target.
//   2. Validate it.
//   3. Add Authorization: Key FAL_KEY.
//   4. Forward the request.
//   5. Return the fal.ai response.
//
// This follows fal.ai's documented custom Express proxy
// pattern.
// =========================================================

app.all(
  "/api/fal/proxy",
  express.raw({
    type: "*/*",
    limit: "50mb"
  }),
  async (req, res) => {

    // -------------------------------------------------------
    // Method validation
    // -------------------------------------------------------

    const allowedMethods = [
      "GET",
      "POST",
      "PUT",
      "DELETE"
    ];

    if (!allowedMethods.includes(req.method)) {
      return res.status(405).json({
        error: "Method Not Allowed"
      });
    }

    // -------------------------------------------------------
    // Get target URL
    // -------------------------------------------------------

    const targetUrl =
      req.headers["x-fal-target-url"];

    if (!targetUrl) {
      console.error(
        "[proxy] Missing x-fal-target-url"
      );

      return res.status(400).json({
        error:
          "Missing x-fal-target-url header"
      });
    }

    // -------------------------------------------------------
    // Validate target
    // -------------------------------------------------------

    if (!isAllowedTarget(targetUrl)) {
      console.error(
        "[proxy] Blocked target:",
        targetUrl
      );

      return res.status(412).json({
        error:
          "Target URL is not allowed"
      });
    }

    // -------------------------------------------------------
    // Check API key
    // -------------------------------------------------------

    if (!FAL_KEY) {
      console.error(
        "[proxy] FAL_KEY is missing"
      );

      return res.status(500).json({
        error:
          "Server is missing FAL_KEY"
      });
    }

    // -------------------------------------------------------
    // Forward request
    // -------------------------------------------------------

    try {

      const target = new URL(targetUrl);

      /*
       * Copy the incoming headers.
       *
       * Remove browser/proxy-specific headers that should
       * not be forwarded unchanged.
       */

      const forwardHeaders = {
        ...req.headers
      };

      delete forwardHeaders.host;
      delete forwardHeaders.connection;
      delete forwardHeaders["content-length"];

      /*
       * fal.ai authentication.
       *
       * The API key NEVER goes back to the browser.
       */

      forwardHeaders.authorization =
        `Key ${FAL_KEY}`;

      /*
       * The upstream host must match the target.
       */

      forwardHeaders.host =
        target.host;

      console.log(
        `[proxy] ${req.method} ${targetUrl}`
      );

      // -----------------------------------------------------
      // Make upstream request
      // -----------------------------------------------------

      const upstream =
        await fetch(
          targetUrl,
          {
            method: req.method,

            headers:
              forwardHeaders,

            body:
              ["GET", "HEAD"].includes(
                req.method
              )
                ? undefined
                : req.body,

            redirect: "follow"
          }
        );

      console.log(
        `[proxy] ${upstream.status} ${targetUrl}`
      );

      // -----------------------------------------------------
      // Copy response headers
      // -----------------------------------------------------

      upstream.headers.forEach(
        (value, key) => {

          /*
           * Let Node/Express manage these.
           */

          if (
            key === "content-length" ||
            key === "content-encoding" ||
            key === "transfer-encoding" ||
            key === "connection"
          ) {
            return;
          }

          res.setHeader(
            key,
            value
          );
        }
      );

      // -----------------------------------------------------
      // Return status
      // -----------------------------------------------------

      res.status(
        upstream.status
      );

      // -----------------------------------------------------
      // Return body
      // -----------------------------------------------------

      const buffer =
        await upstream.arrayBuffer();

      res.send(
        Buffer.from(buffer)
      );

    } catch (error) {

      console.error(
        "[proxy] Request failed:",
        error
      );

      if (!res.headersSent) {

        res.status(502).json({
          error:
            "Upstream request to fal.ai failed",
          message:
            error.message
        });

      }
    }
  }
);

// =========================================================
// Also accept /api/fal/proxy/*
//
// Some versions of @fal-ai/client can append a path after
// the configured proxy URL. We support both forms.
// =========================================================

app.all(
  "/api/fal/proxy/*",
  express.raw({
    type: "*/*",
    limit: "50mb"
  }),
  async (req, res) => {

    const targetUrl =
      req.headers["x-fal-target-url"];

    if (!targetUrl) {

      return res.status(400).json({
        error:
          "Missing x-fal-target-url header"
      });

    }

    if (!isAllowedTarget(targetUrl)) {

      return res.status(412).json({
        error:
          "Target URL is not allowed"
      });

    }

    if (!FAL_KEY) {

      return res.status(500).json({
        error:
          "Server is missing FAL_KEY"
      });

    }

    try {

      const target =
        new URL(targetUrl);

      const forwardHeaders = {
        ...req.headers
      };

      delete forwardHeaders.host;
      delete forwardHeaders.connection;
      delete forwardHeaders["content-length"];

      forwardHeaders.authorization =
        `Key ${FAL_KEY}`;

      forwardHeaders.host =
        target.host;

      console.log(
        `[proxy] ${req.method} ${targetUrl}`
      );

      const upstream =
        await fetch(
          targetUrl,
          {
            method: req.method,

            headers:
              forwardHeaders,

            body:
              ["GET", "HEAD"].includes(
                req.method
              )
                ? undefined
                : req.body,

            redirect: "follow"
          }
        );

      console.log(
        `[proxy] upstream status: ${upstream.status}`
      );

      upstream.headers.forEach(
        (value, key) => {

          if (
            key === "content-length" ||
            key === "content-encoding" ||
            key === "transfer-encoding" ||
            key === "connection"
          ) {
            return;
          }

          res.setHeader(
            key,
            value
          );

        }
      );

      res.status(
        upstream.status
      );

      const buffer =
        await upstream.arrayBuffer();

      res.send(
        Buffer.from(buffer)
      );

    } catch (error) {

      console.error(
        "[proxy] Error:",
        error
      );

      res.status(502).json({
        error:
          "Upstream request to fal.ai failed",
        message:
          error.message
      });

    }
  }
);

// =========================================================
// Static frontend
// =========================================================

app.use(
  express.static(
    path.join(__dirname)
  )
);

// =========================================================
// 404
// =========================================================

app.use(
  (req, res) => {

    res.status(404).json({
      error: "Not found"
    });

  }
);

// =========================================================
// Start
// =========================================================

app.listen(
  PORT,
  () => {

    console.log("");
    console.log(
      "========================================"
    );
    console.log(
      "        ANONYMOUX STUDIO"
    );
    console.log(
      "========================================"
    );
    console.log(
      `Port: ${PORT}`
    );
    console.log(
      "FAL proxy: ENABLED"
    );
    console.log(
      `FAL_KEY: ${
        FAL_KEY
          ? "configured"
          : "MISSING"
      }`
    );
    console.log(
      "Realtime WebSocket: handled by @fal-ai/client"
    );
    console.log(
      "========================================"
    );
    console.log("");

  }
);
